blank_issues_enabled: false
contact_links:
  - name: 💬 Questions / Help
    url: https://faq.locize.com/
    about: If you have questions, please check https://faq.locize.com/ or https://www.i18next.com/ or https://react.i18next.com/ or https://stackoverflow.com/ or similar or send an email to support@locize.com